In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("ML2.zip")
df

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  \
0        Email 1    0   0    1    0    0   0    2    0    0  ...         0   
1        Email 2    8  13   24    6    6   2  102    1   27  ...         0   
2        Email 3    0   0    1    0    0   0    8    0    0  ...         0   
3        Email 4    0   5   22    0    5   1   51    2   10  ...         0   
4        Email 5    7   6   17    1    5   2   57    0    9  ...         0   
...          ...  ...  ..  ...  ...  ...  ..  ...  ...  ...  ...       ...   
5167  Email 5168    2   2    2    3    0   0   32    0    0  ...         0   
5168  Email 5169   35  27   11    2    6   5  151    4    3  ...         0   
5169  Email 5170    0   0    1    1    0   0   11    0    0  ...         0   
5170  Email 5171    2   7    1    0    2   1   28    2    0  ...         0   
5171  Email 5172   22  24    5    1    6   5  148    8    2  ...         0   

      jay  valued  lay  infrastructure  military  allowing  ff  dry  \
0       0       0    0               0         0         0   0    0   
1       0       0    0               0         0         0   1    0   
2       0       0    0               0         0         0   0    0   
3       0       0    0               0         0         0   0    0   
4       0       0    0               0         0         0   1    0   
...   ...     ...  ...             ...       ...       ...  ..  ...   
5167    0       0    0               0         0         0   0    0   
5168    0       0    0               0         0         0   1    0   
5169    0       0    0               0         0         0   0    0   
5170    0       0    0               0         0         0   1    0   
5171    0       0    0               0         0         0   0    0   

      Prediction  
0              0  
1              0  
2              0  
3              0  
4              0  
...          ...  
5167           0  
5168           0  
5169           1  
5170           1  
5171           0  

[5172 rows x 3002 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5172 entries, 0 to 5171
Columns: 3002 entries, Email No. to Prediction
dtypes: int64(3001), object(1)
memory usage: 118.5+ MB


In [4]:
df.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

In [5]:
df.dtypes

Email No.     object
the            int64
to             int64
ect            int64
and            int64
               ...  
military       int64
allowing       int64
ff             int64
dry            int64
Prediction     int64
Length: 3002, dtype: object

In [8]:
df = df.drop(["Email No."] , axis=1)
df

the  to  ect  and  for  of    a  you  hou  in  ...  connevey  jay  \
0       0   0    1    0    0   0    2    0    0   0  ...         0    0   
1       8  13   24    6    6   2  102    1   27  18  ...         0    0   
2       0   0    1    0    0   0    8    0    0   4  ...         0    0   
3       0   5   22    0    5   1   51    2   10   1  ...         0    0   
4       7   6   17    1    5   2   57    0    9   3  ...         0    0   
...   ...  ..  ...  ...  ...  ..  ...  ...  ...  ..  ...       ...  ...   
5167    2   2    2    3    0   0   32    0    0   5  ...         0    0   
5168   35  27   11    2    6   5  151    4    3  23  ...         0    0   
5169    0   0    1    1    0   0   11    0    0   1  ...         0    0   
5170    2   7    1    0    2   1   28    2    0   8  ...         0    0   
5171   22  24    5    1    6   5  148    8    2  23  ...         0    0   

      valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0          0    0               0         0         0   0    0           0  
1          0    0               0         0         0   1    0           0  
2          0    0               0         0         0   0    0           0  
3          0    0               0         0         0   0    0           0  
4          0    0               0         0         0   1    0           0  
...      ...  ...             ...       ...       ...  ..  ...         ...  
5167       0    0               0         0         0   0    0           0  
5168       0    0               0         0         0   1    0           0  
5169       0    0               0         0         0   0    0           1  
5170       0    0               0         0         0   1    0           1  
5171       0    0               0         0         0   0    0           0  

[5172 rows x 3001 columns]

In [9]:
df.isna().sum()

the           0
to            0
ect           0
and           0
for           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3001, dtype: int64

In [11]:
#Seperating the feature and label
x = df.drop(["Prediction"] , axis = 1)
y = df["Prediction"]
x[:5],y[:5]

(   the  to  ect  and  for  of    a  you  hou  in  ...  enhancements  connevey  \
 0    0   0    1    0    0   0    2    0    0   0  ...             0         0   
 1    8  13   24    6    6   2  102    1   27  18  ...             0         0   
 2    0   0    1    0    0   0    8    0    0   4  ...             0         0   
 3    0   5   22    0    5   1   51    2   10   1  ...             0         0   
 4    7   6   17    1    5   2   57    0    9   3  ...             0         0   
 
    jay  valued  lay  infrastructure  military  allowing  ff  dry  
 0    0       0    0               0         0         0   0    0  
 1    0       0    0               0         0         0   1    0  
 2    0       0    0               0         0         0   0    0  
 3    0       0    0               0         0         0   0    0  
 4    0       0    0               0         0         0   1    0  
 
 [5 rows x 3000 columns],
 0    0
 1    0
 2    0
 3    0
 4    0
 Name: Prediction, dtype: int6

In [12]:
#Spliting the dataset
from sklearn.model_selection import train_test_split
x_train , x_test ,y_train , y_test = train_test_split(x, y , test_size=0.3, random_state= 42)

In [20]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
model1 = KNeighborsClassifier(n_neighbors = 2)
model1.fit(x_train , y_train)

KNeighborsClassifier(n_neighbors=2)

In [22]:
y_pred = model1.predict(x_test)
y_pred

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [25]:
target_name = ["Not spam" , "Spam"]
from sklearn.metrics import classification_report
print(classification_report(y_test , y_pred , target_names = target_name))

              precision    recall  f1-score   support

    Not spam       0.88      0.93      0.91      1097
        Spam       0.82      0.70      0.75       455

    accuracy                           0.87      1552
   macro avg       0.85      0.82      0.83      1552
weighted avg       0.86      0.87      0.86      1552



In [26]:
from sklearn import metrics 
confusion_matrix = metrics .confusion_matrix(y_test , y_pred)
confusion_matrix

array([[1025,   72],
       [ 136,  319]], dtype=int64)

In [28]:
#SVM(kernel = linear)
from sklearn import svm
model2 = svm.SVC(kernel = 'linear')
model2.fit(x_train , y_train)

SVC(kernel='linear')

In [29]:
y_pred = model2.predict(x_test)
y_pred

array([0, 0, 1, ..., 0, 0, 1], dtype=int64)

In [30]:
print(classification_report(y_test , y_pred , target_names = target_name))

              precision    recall  f1-score   support

    Not spam       0.97      0.97      0.97      1097
        Spam       0.92      0.93      0.93       455

    accuracy                           0.96      1552
   macro avg       0.95      0.95      0.95      1552
weighted avg       0.96      0.96      0.96      1552



In [31]:
confusion_matrix = metrics .confusion_matrix(y_test , y_pred)
confusion_matrix

array([[1062,   35],
       [  32,  423]], dtype=int64)

In [33]:
model3 = svm.SVC(kernel = 'rbf')
model3.fit(x_train , y_train)

SVC()

In [34]:
y_pred = model3.predict(x_test)
y_pred

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [35]:
print(classification_report(y_test , y_pred , target_names = target_name))

              precision    recall  f1-score   support

    Not spam       0.79      0.99      0.88      1097
        Spam       0.92      0.36      0.52       455

    accuracy                           0.80      1552
   macro avg       0.85      0.67      0.70      1552
weighted avg       0.83      0.80      0.77      1552



In [36]:
confusion_matrix = metrics .confusion_matrix(y_test , y_pred)
confusion_matrix

array([[1082,   15],
       [ 290,  165]], dtype=int64)